# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Data(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, image: List[str]=None):  # noqa: E501
        """Data - a model defined in Swagger

        :param image: The image of this Data.  # noqa: E501
        :type image: List[str]
        """
        self.swagger_types = {
            'image': List[str]
        }

        self.attribute_map = {
            'image': 'image'
        }

        self._image = image

    @classmethod
    def from_dict(cls, dikt) -> 'Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The data of this Data.  # noqa: E501
        :rtype: Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image(self) -> List[str]:
        """Gets the image of this Data.


        :return: The image of this Data.
        :rtype: List[str]
        """
        return self._image

    @image.setter
    def image(self, image: List[str]):
        """Sets the image of this Data.


        :param image: The image of this Data.
        :type image: List[str]
        """

        self._image = image
