# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Matrix(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, method: str=None, val: List[str]=None):  # noqa: E501
        """Matrix - a model defined in Swagger

        :param method: The method of this Matrix.  # noqa: E501
        :type method: str
        :param val: The val of this Matrix.  # noqa: E501
        :type val: List[str]
        """
        self.swagger_types = {
            'method': str,
            'val': List[str]
        }

        self.attribute_map = {
            'method': 'method',
            'val': 'val'
        }

        self._method = method
        self._val = val

    @classmethod
    def from_dict(cls, dikt) -> 'Matrix':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The matrix of this Matrix.  # noqa: E501
        :rtype: Matrix
        """
        return util.deserialize_model(dikt, cls)

    @property
    def method(self) -> str:
        """Gets the method of this Matrix.


        :return: The method of this Matrix.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this Matrix.


        :param method: The method of this Matrix.
        :type method: str
        """

        self._method = method

    @property
    def val(self) -> List[str]:
        """Gets the val of this Matrix.


        :return: The val of this Matrix.
        :rtype: List[str]
        """
        return self._val

    @val.setter
    def val(self, val: List[str]):
        """Sets the val of this Matrix.


        :param val: The val of this Matrix.
        :type val: List[str]
        """

        self._val = val
