---
swagger: "2.0"
info:
  description: "This is the API for the project Reconnaissance Nombre"
  version: "1.0.0"
  title: "Reconnaissance Nombre"
  contact:
    email: "valerian.acier@imerir.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/"
tags:
- name: "Manage Training"
  description: "Manage training"
- name: "TestData"
  description: "Evaluate Data"
- name: "GetData"
  description: "Get informations"
schemes:
- "https"
- "http"
paths:
  /add:
    post:
      tags:
      - "Manage Training"
      summary: "Add a train data in database"
      description: "Add a train data in database\n"
      operationId: "add_data_master_add_data_add_data"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "dataTrain"
        description: "Data information"
        required: true
        schema:
          $ref: "#/definitions/dataTrain"
      responses:
        200:
          description: "The data has been added"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.manage_training_controller"
  /test:
    post:
      tags:
      - "TestData"
      summary: "Add a train data in database"
      description: "Add a train data in database\n"
      operationId: "test_data_master_test_data_test_data"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "image"
        description: "Data information"
        required: true
        schema:
          $ref: "#/definitions/data"
      responses:
        200:
          description: "return solution"
          schema:
            $ref: "#/definitions/solution"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.test_data_controller"
  /getMatrix:
    get:
      tags:
      - "GetData"
      summary: "Get Confusion Matrix of all Algorithms"
      description: "Get Confusion Matrix of all Algorithms\n"
      operationId: "get_maxtrix_master_get_maxtrix_get_maxtrix"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "return solution"
          schema:
            $ref: "#/definitions/matrix"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.get_data_controller"
  /startTrain:
    post:
      tags:
      - "Manage Training"
      summary: "Get Confusion Matrix of all Algorithms"
      description: "Get Confusion Matrix of all Algorithms\n"
      operationId: "start_train_master_start_train_start_train"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success, train start"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.manage_training_controller"
definitions:
  data:
    type: "array"
    items:
      type: "integer"
    example: "[1,1,1,1,1,0,1,0,1,0,1,0,1,1,1]"
  matrix:
    type: "array"
    items:
      type: "integer"
    example: "[[1,1,1,1],[1,0,1,0],[1,0,1,0],[1,1,1,1]]"
  solution:
    type: "integer"
    example: 1
  dataTrain:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/data"
      solution:
        $ref: "#/definitions/solution"
    example:
      data:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 0
      - 1
      - 0
      - 1
      - 0
      - 1
      - 0
      - 1
      - 1
      - 1
      solution:5: null
